name: Keep Render Services Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:

      - name: Ping FastAPI ML Service
        run: |
          for i in 1 2 3
          do
            curl -s https://prediction-model-wi0s.onrender.com/predictions && break
            echo "Retry FastAPI $i..."
            sleep 10
          done


      - name: Ping Node.js Backend
        run: |
          for i in 1 2 3
          do
            curl -s https://node-backend-xuum.onrender.com/api/predictions/insights && break
            echo "Retry Node Backend $i..."
            sleep 10
          done
